/**
 * Catálogo de diagramas disponibles en «Añadir diagrama».
 *
 * `support` indica cómo lo dibuja PlantUML:
 * - native: PlantUML tiene sintaxis propia para este diagrama.
 * - adapted: PlantUML no lo trae como tipo propio; la plantilla lo construye
 *   con elementos de otro diagrama (se explica en `note`).
 * - unavailable: el motor de PlantUML para navegador aún no lo dibuja.
 *
 * Todas las plantillas se probaron con @plantuml/core 1.2026.8.
 *
 * `visual` marca los tipos que tendrán editor visual (arrastrar y soltar).
 */
export type UmlCategory = 'uml' | 'architecture' | 'process'
export type UmlSupport = 'native' | 'adapted' | 'unavailable'

export type UmlDiagramType = {
  id: string
  name: string
  /** Nombre en inglés, como aparece en la bibliografía y en PlantUML. */
  english: string
  category: UmlCategory
  support: UmlSupport
  note?: string
  visual?: boolean
  template: string
}

export const UML_CATEGORIES: Array<{ id: UmlCategory; name: string }> = [
  { id: 'uml', name: 'Diagramas de Lenguaje Unificado de Modelado (UML)' },
  { id: 'architecture', name: 'Diagramas de Arquitectura y Datos' },
  { id: 'process', name: 'Diagramas de Procesos, Gestión y Diseño' },
]

const lines = (...rows: string[]) => rows.join('\n')

export const UML_DIAGRAM_TYPES: UmlDiagramType[] = [
  // --- UML -------------------------------------------------------------------
  {
    id: 'class', name: 'Diagrama de clases', english: 'Class Diagram', category: 'uml', support: 'native', visual: true,
    template: lines(
      '@startuml',
      'title Diagrama de clases',
      'class Usuario {',
      '  - id: UUID',
      '  - email: String',
      '  + iniciarSesion(clave: String): boolean',
      '}',
      'class Tablero {',
      '  - nombre: String',
      '  + agregarTarea(t: Tarea)',
      '}',
      'class Tarea {',
      '  - titulo: String',
      '  - prioridad: Prioridad',
      '}',
      'enum Prioridad {',
      '  ALTA',
      '  MEDIA',
      '  BAJA',
      '}',
      'Usuario "1" -- "*" Tablero : posee >',
      'Tablero "1" *-- "*" Tarea : contiene >',
      'Tarea --> Prioridad',
      '@enduml',
    ),
  },
  {
    id: 'object', name: 'Diagrama de objetos', english: 'Object Diagram', category: 'uml', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama de objetos',
      'object "ana : Usuario" as ana {',
      '  email = "ana@empresa.cl"',
      '}',
      'object "sprint1 : Tablero" as sprint1 {',
      '  nombre = "Sprint 1"',
      '}',
      'object "t12 : Tarea" as t12 {',
      '  titulo = "Login"',
      '  prioridad = ALTA',
      '}',
      'ana --> sprint1 : posee',
      'sprint1 *-- t12',
      '@enduml',
    ),
  },
  {
    id: 'component', name: 'Diagrama de componentes', english: 'Component Diagram', category: 'uml', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama de componentes',
      'package "Frontend" {',
      '  [Aplicación web] as web',
      '}',
      'package "Backend" {',
      '  [API REST] as api',
      '  [Servicio de autenticación] as auth',
      '}',
      'database "Base de datos" as db',
      'interface HTTPS',
      'web --> HTTPS',
      'HTTPS - api',
      'api --> auth',
      'api --> db : SQL',
      '@enduml',
    ),
  },
  {
    id: 'deployment', name: 'Diagrama de despliegue', english: 'Deployment Diagram', category: 'uml', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama de despliegue',
      'actor Usuario',
      'node "Navegador" as browser {',
      '  artifact "app.js"',
      '}',
      'cloud "Proveedor cloud" {',
      '  node "Servidor web" as web',
      '  node "Servidor de aplicaciones" as app {',
      '    artifact "api.jar"',
      '  }',
      '  database "PostgreSQL" as db',
      '}',
      'Usuario --> browser',
      'browser --> web : HTTPS',
      'web --> app',
      'app --> db : TCP 5432',
      '@enduml',
    ),
  },
  {
    id: 'package', name: 'Diagrama de paquetes', english: 'Package Diagram', category: 'uml', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama de paquetes',
      'package "presentacion" {',
      '  class Vista',
      '}',
      'package "aplicacion" {',
      '  class Servicio',
      '}',
      'package "dominio" {',
      '  class Entidad',
      '}',
      'package "infraestructura" {',
      '  class Repositorio',
      '}',
      '"presentacion" ..> "aplicacion" : <<use>>',
      '"aplicacion" ..> "dominio" : <<use>>',
      '"infraestructura" ..> "dominio" : <<import>>',
      '@enduml',
    ),
  },
  {
    id: 'composite', name: 'Diagrama de estructura compuesta', english: 'Composite Structure Diagram', category: 'uml', support: 'adapted',
    note: 'Se representa con componentes, partes internas y puertos.',
    template: lines(
      '@startuml',
      'title Diagrama de estructura compuesta',
      'component "Pedido" as pedido {',
      '  portin entrada',
      '  portout salida',
      '  component "carrito : Carrito" as carrito',
      '  component "pago : Pago" as pago',
      '  entrada --> carrito',
      '  carrito --> pago',
      '  pago --> salida',
      '}',
      '[Cliente] --> entrada',
      'salida --> [Despacho]',
      '@enduml',
    ),
  },
  {
    id: 'profile', name: 'Diagrama de perfil', english: 'Profile Diagram', category: 'uml', support: 'adapted',
    note: 'Se representa con metaclases, estereotipos y extensiones en un diagrama de clases.',
    template: lines(
      '@startuml',
      'title Diagrama de perfil',
      'package "Perfil Web" <<profile>> {',
      '  metaclass Class',
      '  stereotype Controlador {',
      '    ruta: String',
      '  }',
      '  stereotype Entidad {',
      '    tabla: String',
      '  }',
      '}',
      'Class <|-- Controlador : <<extension>>',
      'Class <|-- Entidad : <<extension>>',
      '@enduml',
    ),
  },
  {
    id: 'usecase', name: 'Diagrama de casos de uso', english: 'Use Case Diagram', category: 'uml', support: 'native', visual: true,
    template: lines(
      '@startuml',
      'title Diagrama de casos de uso',
      'left to right direction',
      'actor Cliente',
      'actor "Administrador" as admin',
      'rectangle "Tienda en línea" {',
      '  usecase "Buscar producto" as UC1',
      '  usecase "Comprar" as UC2',
      '  usecase "Pagar" as UC3',
      '  usecase "Gestionar catálogo" as UC4',
      '}',
      'Cliente --> UC1',
      'Cliente --> UC2',
      'UC2 ..> UC3 : <<include>>',
      'admin --> UC4',
      '@enduml',
    ),
  },
  {
    id: 'sequence', name: 'Diagrama de secuencia', english: 'Sequence Diagram', category: 'uml', support: 'native', visual: true,
    template: lines(
      '@startuml',
      'title Diagrama de secuencia',
      'actor Usuario',
      'participant "Aplicación" as app',
      'participant "API" as api',
      'database "Base de datos" as db',
      'Usuario -> app : Ingresa credenciales',
      'app -> api : POST /login',
      'api -> db : Buscar usuario',
      'db --> api : Usuario',
      'alt credenciales válidas',
      '  api --> app : 200 + token',
      '  app --> Usuario : Muestra el tablero',
      'else credenciales inválidas',
      '  api --> app : 401',
      '  app --> Usuario : Muestra error',
      'end',
      '@enduml',
    ),
  },
  {
    id: 'activity', name: 'Diagrama de actividades', english: 'Activity Diagram', category: 'uml', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama de actividades',
      'start',
      ':Recibir pedido;',
      'if (¿Hay stock?) then (sí)',
      '  :Reservar productos;',
      '  fork',
      '    :Cobrar;',
      '  fork again',
      '    :Preparar despacho;',
      '  end fork',
      '  :Enviar pedido;',
      'else (no)',
      '  :Notificar al cliente;',
      'endif',
      'stop',
      '@enduml',
    ),
  },
  {
    id: 'state', name: 'Diagrama de estados', english: 'State Machine Diagram', category: 'uml', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama de estados',
      '[*] --> Pendiente',
      'Pendiente --> EnProgreso : iniciar',
      'EnProgreso --> EnRevision : enviar a revisión',
      'EnRevision --> EnProgreso : cambios solicitados',
      'EnRevision --> Completada : aprobar',
      'Completada --> [*]',
      'state EnProgreso {',
      '  [*] --> Desarrollo',
      '  Desarrollo --> Pruebas',
      '}',
      '@enduml',
    ),
  },
  {
    id: 'communication', name: 'Diagrama de comunicación', english: 'Communication Diagram', category: 'uml', support: 'adapted',
    note: 'Se representa con objetos enlazados y mensajes numerados.',
    template: lines(
      '@startuml',
      'title Diagrama de comunicación',
      'left to right direction',
      'rectangle ":Cliente" as cliente',
      'rectangle ":Carrito" as carrito',
      'rectangle ":Pedido" as pedido',
      'rectangle ":Pago" as pago',
      'cliente -- carrito : 1: agregarProducto()',
      'carrito -- pedido : 2: confirmar()',
      'pedido -- pago : 3: cobrar()',
      'pago -- pedido : 3.1: confirmación',
      '@enduml',
    ),
  },
  {
    id: 'timing', name: 'Diagrama de tiempos', english: 'Timing Diagram', category: 'uml', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama de tiempos',
      'robust "Servidor" as srv',
      'concise "Usuario" as usr',
      '@0',
      'srv is Inactivo',
      'usr is Esperando',
      '@100',
      'usr is Solicitando',
      'srv is Procesando',
      '@300',
      'srv is Respondiendo',
      '@400',
      'srv is Inactivo',
      'usr is Leyendo',
      '@enduml',
    ),
  },
  {
    id: 'interaction-overview', name: 'Diagrama global de interacción', english: 'Interaction Overview Diagram', category: 'uml', support: 'adapted',
    note: 'Se representa con un diagrama de actividades cuyos pasos referencian interacciones (ref).',
    template: lines(
      '@startuml',
      'title Diagrama global de interacción',
      'start',
      ':ref: Iniciar sesión;',
      'if (¿Autenticado?) then (sí)',
      '  :ref: Cargar tablero;',
      '  :ref: Sincronizar en tiempo real;',
      'else (no)',
      '  :ref: Recuperar contraseña;',
      'endif',
      'stop',
      '@enduml',
    ),
  },

  // --- Arquitectura y datos ---------------------------------------------------
  {
    id: 'aws', name: 'Diagrama de arquitectura de AWS', english: 'AWS Architecture Diagram', category: 'architecture', support: 'adapted',
    note: 'Usa nodos y estereotipos de AWS; los íconos oficiales de AWS no vienen incluidos.',
    template: lines(
      '@startuml',
      'title Arquitectura en AWS',
      'actor Usuario',
      'cloud "AWS" {',
      '  node "CloudFront" <<CDN>> as cdn',
      '  storage "S3" <<Bucket>> as s3',
      '  node "API Gateway" <<API>> as apigw',
      '  node "Lambda" <<Función>> as lambda',
      '  database "RDS PostgreSQL" <<Base de datos>> as rds',
      '}',
      'Usuario --> cdn',
      'cdn --> s3 : estáticos',
      'Usuario --> apigw : HTTPS',
      'apigw --> lambda',
      'lambda --> rds',
      '@enduml',
    ),
  },
  {
    id: 'gcp', name: 'Diagrama de arquitectura de GCP', english: 'GCP Architecture Diagram', category: 'architecture', support: 'adapted',
    note: 'Usa nodos y estereotipos de Google Cloud; los íconos oficiales de GCP no vienen incluidos.',
    template: lines(
      '@startuml',
      'title Arquitectura en Google Cloud',
      'actor Usuario',
      'cloud "Google Cloud" {',
      '  node "Cloud Load Balancing" <<Balanceador>> as lb',
      '  node "Cloud Run" <<Contenedor>> as run',
      '  queue "Pub/Sub" <<Mensajería>> as pubsub',
      '  database "Cloud SQL" <<Base de datos>> as sql',
      '  storage "Cloud Storage" <<Bucket>> as gcs',
      '}',
      'Usuario --> lb : HTTPS',
      'lb --> run',
      'run --> sql',
      'run --> gcs',
      'run --> pubsub : eventos',
      '@enduml',
    ),
  },
  {
    id: 'c4', name: 'Diagrama C4', english: 'C4 Diagram', category: 'architecture', support: 'adapted',
    note: 'Nivel de contenedores del modelo C4, con estereotipos C4 sobre elementos de PlantUML.',
    template: lines(
      '@startuml',
      'title C4 · Contenedores',
      'actor "Usuario" <<Persona>> as user',
      'rectangle "Sistema de gestión" <<Sistema>> {',
      '  rectangle "Aplicación web\\n[React]\\nInterfaz para el usuario" <<Contenedor>> as spa',
      '  rectangle "API\\n[Supabase]\\nAutenticación y datos" <<Contenedor>> as api',
      '  database "Base de datos\\n[PostgreSQL]" <<Contenedor>> as db',
      '}',
      'rectangle "Correo\\n[SMTP]" <<Sistema externo>> as mail',
      'user --> spa : Usa [HTTPS]',
      'spa --> api : Lee y escribe [JSON/HTTPS]',
      'api --> db : SQL',
      'api --> mail : Envía correos',
      '@enduml',
    ),
  },
  {
    id: 'dfd', name: 'Diagrama de flujo de datos', english: 'Data Flow Diagram', category: 'architecture', support: 'adapted',
    note: 'Entidades externas como rectángulos, procesos como círculos y almacenes de datos como bases de datos.',
    template: lines(
      '@startuml',
      'title Diagrama de flujo de datos · Nivel 1',
      'left to right direction',
      'rectangle "Cliente" as cliente',
      'usecase "1.0\\nRegistrar pedido" as p1',
      'usecase "2.0\\nProcesar pago" as p2',
      'database "D1 Pedidos" as d1',
      'rectangle "Pasarela de pago" as pasarela',
      'cliente --> p1 : datos del pedido',
      'p1 --> d1 : pedido',
      'p1 --> p2 : monto',
      'p2 --> pasarela : cobro',
      'pasarela --> p2 : confirmación',
      'p2 --> cliente : comprobante',
      '@enduml',
    ),
  },
  {
    id: 'er', name: 'Diagrama entidad-relación', english: 'ER Diagram', category: 'architecture', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama entidad-relación',
      'hide circle',
      'skinparam linetype ortho',
      'entity "usuario" as usuario {',
      '  * id : uuid <<PK>>',
      '  --',
      '  * email : text',
      '  nombre : text',
      '}',
      'entity "tablero" as tablero {',
      '  * id : uuid <<PK>>',
      '  --',
      '  * owner_id : uuid <<FK>>',
      '  * nombre : text',
      '}',
      'entity "tarea" as tarea {',
      '  * id : uuid <<PK>>',
      '  --',
      '  * tablero_id : uuid <<FK>>',
      '  * titulo : text',
      '  fecha_fin : date',
      '}',
      'usuario ||--o{ tablero : posee',
      'tablero ||--o{ tarea : contiene',
      '@enduml',
    ),
  },

  // --- Procesos, gestión y diseño --------------------------------------------
  {
    id: 'bpmn', name: 'Diagrama BPMN', english: 'BPMN Diagram', category: 'process', support: 'adapted',
    note: 'Se representa con un diagrama de actividades con carriles (swimlanes) por participante.',
    template: lines(
      '@startuml',
      'title Proceso de compra (BPMN)',
      '|Cliente|',
      'start',
      ':Realizar pedido;',
      '|Ventas|',
      ':Validar pedido;',
      'if (¿Pedido válido?) then (sí)',
      '  |Bodega|',
      '  :Preparar productos;',
      '  :Despachar;',
      '  |Cliente|',
      '  :Recibir pedido;',
      'else (no)',
      '  |Ventas|',
      '  :Rechazar pedido;',
      'endif',
      'stop',
      '@enduml',
    ),
  },
  {
    id: 'flowchart', name: 'Diagrama de flujo', english: 'Flowchart Diagram', category: 'process', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama de flujo',
      'start',
      ':Leer número N;',
      'if (N es par?) then (sí)',
      '  :Mostrar "par";',
      'else (no)',
      '  :Mostrar "impar";',
      'endif',
      'while (¿Otro número?) is (sí)',
      '  :Leer número N;',
      'endwhile (no)',
      'stop',
      '@enduml',
    ),
  },
  {
    id: 'gantt', name: 'Diagrama de Gantt', english: 'Gantt', category: 'process', support: 'native',
    template: lines(
      '@startgantt',
      'title Plan del proyecto',
      'printscale weekly',
      'saturday are closed',
      'sunday are closed',
      'Project starts 2026-11-02',
      '[Levantamiento] requires 5 days',
      '[Diseño] requires 8 days',
      '[Diseño] starts at [Levantamiento]\'s end',
      '[Desarrollo] requires 15 days',
      '[Desarrollo] starts at [Diseño]\'s end',
      '[Pruebas] requires 5 days',
      '[Pruebas] starts at [Desarrollo]\'s end',
      '[Entrega] happens at [Pruebas]\'s end',
      '@endgantt',
    ),
  },
  {
    id: 'network', name: 'Diagrama de red', english: 'Network', category: 'process', support: 'native',
    template: lines(
      '@startnwdiag',
      'title Diagrama de red',
      'nwdiag {',
      '  network dmz {',
      '    address = "210.x.x.x/24"',
      '    web01 [address = "210.x.x.1"];',
      '    web02 [address = "210.x.x.2"];',
      '  }',
      '  network interna {',
      '    address = "172.16.0.0/24";',
      '    web01 [address = "172.16.0.1"];',
      '    web02 [address = "172.16.0.2"];',
      '    db01 [address = "172.16.0.100"];',
      '  }',
      '}',
      '@endnwdiag',
    ),
  },
  {
    id: 'requirement', name: 'Diagrama de requisitos', english: 'Requirement Diagram', category: 'process', support: 'adapted',
    note: 'Notación SysML con clases estereotipadas <<requirement>> y relaciones satisfy, derive y verify.',
    template: lines(
      '@startuml',
      'title Diagrama de requisitos',
      'class "REQ-01 Autenticación" as r1 <<requirement>> {',
      '  id = "REQ-01"',
      '  texto = "El usuario debe iniciar sesión con correo y contraseña"',
      '}',
      'class "REQ-02 Bloqueo de cuenta" as r2 <<requirement>> {',
      '  id = "REQ-02"',
      '  texto = "La cuenta se bloquea tras 15 intentos fallidos"',
      '}',
      'class "Servicio de autenticación" as auth <<block>>',
      'class "Prueba de bloqueo" as test <<testCase>>',
      'r2 ..> r1 : <<deriveReqt>>',
      'auth ..> r1 : <<satisfy>>',
      'test ..> r2 : <<verify>>',
      '@enduml',
    ),
  },
  {
    id: 'block', name: 'Diagrama de definición de bloques', english: 'Block Definition Diagram', category: 'process', support: 'adapted',
    note: 'Notación SysML con clases estereotipadas <<block>> y composición de partes.',
    template: lines(
      '@startuml',
      'title Diagrama de definición de bloques',
      'class Vehiculo <<block>> {',
      '  values',
      '  masa: kg',
      '}',
      'class Motor <<block>> {',
      '  potencia: kW',
      '}',
      'class Bateria <<block>> {',
      '  capacidad: kWh',
      '}',
      'class Rueda <<block>>',
      'Vehiculo *-- "1" Motor',
      'Vehiculo *-- "1" Bateria',
      'Vehiculo *-- "4" Rueda',
      '@enduml',
    ),
  },
  {
    // Salt (@startsalt) no viene en el motor de PlantUML para navegador.
    id: 'wireframe', name: 'Esquema de alambre (wireframe)', english: 'Wireframe Diagram', category: 'process', support: 'adapted',
    note: 'Se dibuja con el renderizador propio de la plataforma (el motor de PlantUML para navegador no incluye Salt). El código se genera en sintaxis Salt, compatible con PlantUML.',
    template: lines(
      '@startsalt',
      '{+',
      '  <b>Iniciar sesión',
      '  Correo | "usuario@empresa.cl"',
      '  Contraseña | "****"',
      '  [X] Recordarme',
      '  [Cancelar] | [Ingresar]',
      '}',
      '@endsalt',
    ),
  },
  {
    id: 'mindmap', name: 'Mapa mental', english: 'Mindmap Diagram', category: 'process', support: 'native',
    template: lines(
      '@startmindmap',
      'title Mapa mental del proyecto',
      '* Proyecto',
      '** Alcance',
      '*** Requisitos',
      '*** Entregables',
      '** Equipo',
      '*** Roles',
      '*** Responsables',
      'left side',
      '** Riesgos',
      '*** Técnicos',
      '*** Plazos',
      '** Calidad',
      '*** Pruebas',
      '@endmindmap',
    ),
  },
  {
    id: 'archimate', name: 'Diagrama ArchiMate', english: 'ArchiMate', category: 'process', support: 'native',
    template: lines(
      '@startuml',
      'title Diagrama ArchiMate',
      'archimate #Business "Cliente" as cliente <<business-actor>>',
      'archimate #Business "Gestionar pedidos" as proceso <<business-process>>',
      'archimate #Application "Aplicación de ventas" as app <<application-component>>',
      'archimate #Technology "Servidor" as srv <<technology-node>>',
      'cliente --> proceso',
      'proceso --> app',
      'app --> srv',
      '@enduml',
    ),
  },
  {
    id: 'regex', name: 'Expresiones regulares', english: 'Regex', category: 'process', support: 'native',
    template: lines(
      '@startregex',
      'title Correo electrónico',
      '[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}',
      '@endregex',
    ),
  },
]

export const BLANK_TEMPLATE = lines('@startuml', '', '@enduml')

/** Diagrama vacío con las directivas de su tipo (@startgantt, @startmindmap…). */
export function blankTemplate(type: UmlDiagramType) {
  const rows = type.template.split('\n')
  const start = rows.find((row) => row.startsWith('@start'))
  const end = [...rows].reverse().find((row) => row.startsWith('@end'))
  return start && end ? lines(start, '', end) : BLANK_TEMPLATE
}

export function umlDiagramType(id: string) {
  return UML_DIAGRAM_TYPES.find((type) => type.id === id) ?? null
}
